campus.colemar = 0
campus.samambaia = 1
campus.aparecida = -1
curso.administracao = 0
curso.agronomia = 0
curso.arquitetura = 0
curso.biomedicina = 0
curso.biotecnologia = 0
curso."ciencia da computacao" = 1
curso."ciencias ambientais" = -1
curso."ciencias biologicas" = -1
curso."ciencias contabeis" = -1
curso."ciencias economicas" = 0
curso."comunicacao social" = -1
curso."engenharia ambiental" = -1
curso."engenharia civil" = 0
curso."engenharia de alimentos" = -1
curso."engenharia de computacao" = 1
curso."engenharia de materiais" = -1
curso."engenharia de producao" = -1
curso."engenharia de software" = -1
curso."engenharia de transportes" = -1
curso."engenharia eletrica" = 1
curso."engenharia fisica" = 0
curso."engenharia florestal" = -1
curso."engenharia mecanica" = 1
curso."engenharia quimica" = 0
curso.estatistica = 1
curso.farmacia = -1
curso."fisica bacharelado" = 1
curso."fisica licenciatura" = 1
curso.fisioterapia = -1
curso.geologia = -1
curso."gestao da informacao" = 0
curso."instituto de fisica" = 1
curso."instituto de quimica" = 0
curso."inteligencia artificial" = 1
curso.matematica = 1
curso.medicina = -1
curso.nutricao = -1
curso.psicologia = -1
curso."quimica bacharelado" = 0
curso."quimica licenciatura" = 0
curso."relacoes internacionais" = 0
curso."relacoes publicas" = -1
curso."sistemas de informacao" = 0
curso.zootecnia = -1
disciplina."algebra linear" = 1
disciplina."algebra linear 1" = 1
disciplina."algebra linear 2" = 1
disciplina."analise real" = 1
disciplina."analise real 1" = 1
disciplina."analise real 2" = 1
disciplina.bioestatistica = 0
disciplina."bioestatistica 1" = 0
disciplina."bioestatistica 2" = 0
disciplina."calculo 1a" = 1
disciplina."calculo 1b" = 0
disciplina."calculo 1c" = 0
disciplina."calculo 2a" = 1
disciplina."calculo 2b" = 0
disciplina."calculo 3" = 0
disciplina."calculo 3a" = 1
disciplina."calculo 3b" = 0
disciplina."calculo diferencial" = 1
disciplina."calculo integral" = 1
disciplina."calculo numerico" = 1
disciplina."calculo vetorial" = 1
disciplina.edo = 0
disciplina."educacao matematica inclusiva" = 0
disciplina."equacoes diferenciais parciais" = 0
disciplina.estatistica = 0
disciplina."estatistica 1" = 0
disciplina."estatistica 2" = 0
disciplina."estatistica aplicada a psicologia" = -1
disciplina."estatistica descritiva e probabilidade" = 0
disciplina."estatistica inferencial" = 0
disciplina."fundamentos de analise" = 1
disciplina."geometria analitica" = 1
disciplina."geometria diferencial" = 1
disciplina."geometria espacial" = 0
disciplina.inferencia = 0
disciplina."introducao a analise no rn" = 0
disciplina."introducao a estatistica" = 0
disciplina."introducao a probabilidade" = 0
disciplina."introducao a teoria qualitativa das edo" = 0
disciplina."matematica discreta" = 0
disciplina."matematica financeira" = 0
disciplina.matematicadiscreta = 0
disciplina."nocoes de atuaria" = 0
disciplina.probabilidade = 0
disciplina."probabilidade e estatistica" = 0
disciplina."probabilidade e estatistica a" = 1
disciplina."probabilidade e estatistica b" = 0
disciplina."teoria de grupos" = 1
horario.246m12 = 0
horario.246m23 = 0
horario.246m34 = 0
horario.246m45 = 0
horario.246n23 = -1
horario.246n45 = -1
horario.246t12 = -1
horario.246t23 = 0
horario.246t34 = 0
horario.246t45 = 0
horario.246t56 = 0
horario.24m12 = 0
horario.24m23 = 0
horario.24m34 = 0
horario.24m45 = 0
horario.24m56 = 0
horario.24n23 = -1
horario.24n45 = -1
horario.24t12 = -1
horario.24t23 = 0
horario.24t34 = 0
horario.24t45 = 0
horario.24t56 = 0
horario.25t23 = 0
horario.25t45 = 0
horario.35m12 = 0
horario.35m23 = 0
horario.35m34 = 0
horario.35m45 = 0
horario.35m56 = 0
horario.35n23 = -1
horario.35n34 = -1
horario.35n45 = -1
horario.35t12 = -1
horario.35t23 = 0
horario.35t34 = 0
horario.35t45 = 0
horario.35t56 = 0
horario.36t23 = 0
horario.46m12 = 0
horario.46m23 = 0
horario.46m34 = 0
horario.46m45 = 0
horario.46m56 = 0
horario.46n23 = -1
horario.46n45 = -1
horario.46t12 = -1
horario.46t23 = 0
horario.46t34 = 0
horario.46t45 = 0
horario.46t56 = 0
horario.4t12 = -1
horario.56t23 = 0
horario.5n45 = -1
horario.6m123 = 0
horario.6m23 = 0
horario.6n23 = -1
horario.6t12 = -1
