[campus]
aparecida = -1
colemar = 0
samambaia = 1

[curso]
"ciencia da computacao" = 1
"ciencias ambientais" = -1
"ciencias biologicas" = -1
"ciencias contabeis" = -1
"ciencias economicas" = -1
"comunicacao social" = -1
"engenharia ambiental" = -1
"engenharia civil" = 1
"engenharia de alimentos" = -1
"engenharia de computacao" = 1
"engenharia de materiais" = -1
"engenharia de producao" = -1
"engenharia eletrica" = 1
"engenharia florestal" = -1
"engenharia mecanica" = 1
"engenharia quimica" = 1
"gestao da informacao" = 1
"instituto de fisica" = 1
"inteligencia artificial" = 1
"quimica bacharelado" = 0
"quimica licenciatura" = 0
"relacoes internacionais" = -1
"relacoes publicas" = -1
"sistemas de informacao" = 1
administracao = -1
agronomia = -1
arquitetura = -1
biomedicina = -1
biotecnologia = -1
farmacia = -1
medicina = -1
nutricao = -1
psicologia = -1
zootecnia = -1

[disciplina]
"algebra linear" = 1
"bioestatistica 1" = -1
"calculo 1a" = 1
"calculo 1b" = 0
"calculo 1c" = -1
"calculo 2a" = 1
"calculo 2b" = 0
"calculo 3" = 1
"calculo 3a" = 1
"calculo 3b" = -1
"calculo numerico" = 1
"estatistica 2" = 0
"estatistica aplicada a psicologia" = -1
"estatistica descritiva e probabilidade" = -1
"estatistica inferencial" = -1
"geometria analitica" = 1
"introducao a estatistica" = 0
"matematica discreta" = 1
"probabilidade e estatistica a" = 1
"probabilidade e estatistica" = 1
bioestatistica = 0
edo = 1
estatistica = 0

[horario]
246m12 = 1
246m23 = 1
246m34 = 1
246m45 = 1
24m12 = 1
24m23 = 1
24m34 = 1
24m45 = 1
24m56 = 1
35m12 = 1
35m23 = 1
35m34 = 1
35m45 = 1
35m56 = 1
46m12 = 1
46m23 = 1
46m34 = 1
46m45 = 1
46m56 = 1
6m123 = 1
246t12 = 0
246t34 = 0
24t12 = 0
24t23 = 0
24t34 = 0
24t45 = 0
24t56 = 0
25t23 = 0
25t45 = 0
35t12 = 0
35t23 = 0
35t34 = 0
35t45 = 0
35t56 = 0
46t12 = 0
46t23 = 0
46t34 = 0
46t45 = 0
46t56 = 0
246n23 = -1
246n45 = -1
24n45 = -1
35n23 = -1
35n45 = -1
46n23 = -1
46n45 = -1
