campus.colemar = 0
campus.samambaia = 1
campus.aparecida = -1
curso.administracao = 0
curso.agronomia = 0
curso.arquitetura = 0
curso.biomedicina = 0
curso.biotecnologia = 0
curso."ciencia da computacao" = 0
curso."ciencias ambientais" = 0
curso."ciencias biologicas" = 0
curso."ciencias contabeis" = 0
curso."ciencias economicas" = 0
curso."comunicacao social" = 0
curso."engenharia ambiental" = 0
curso."engenharia civil" = 0
curso."engenharia de alimentos" = 0
curso."engenharia de computacao" = 0
curso."engenharia de materiais" = 0
curso."engenharia de producao" = 0
curso."engenharia de software" = 0
curso."engenharia de transportes" = 0
curso."engenharia eletrica" = 0
curso."engenharia florestal" = 0
curso."engenharia fisica" = 0
curso."engenharia mecanica" = 0
curso."engenharia quimica" = 0
curso.estatistica = 0
curso.farmacia = 0
curso.fisioterapia = 0
curso."fisica bacharelado" = 0
curso."fisica licenciatura" = 0
curso.geologia = 0
curso."gestao da informacao" = 0
curso."instituto de fisica" = 0
curso."instituto de quimica" = 0
curso."inteligencia artificial" = 0
curso.matematica = 0
curso.medicina = 0
curso.nutricao = 0
curso.psicologia = 0
curso."quimica bacharelado" = 0
curso."quimica licenciatura" = 0
curso."relacoes internacionais" = 0
curso."relacoes publicas" = 0
curso."sistemas de informacao" = 0
curso.zootecnia = 0
disciplina."algebra linear" = 1
disciplina."algebra linear 2" = 1
disciplina."algebra linear i" = 1
disciplina."analise real" = 1
disciplina."analise real 2" = 1
disciplina."analise real 1" = 1
disciplina.bioestatistica = -1
disciplina."bioestatistica 1" = -1
disciplina."bioestatistica 2" = -1
disciplina."calculo 1a" = 1
disciplina."calculo 1b" = 0
disciplina."calculo 1c" = 0
disciplina."calculo 2a" = 1
disciplina."calculo 2b" = 0
disciplina."calculo 3" = 1
disciplina."calculo 3a" = 1
disciplina."calculo 3b" = 0
disciplina."calculo diferencial" = 1
disciplina."calculo integral" = 1
disciplina."calculo numerico" = 1
disciplina."calculo vetorial" = 1
disciplina.edo = 1
disciplina."educacao matematica inclusiva" = -1
disciplina."equacoes diferenciais parciais" = 0
disciplina.estatistica = 0
disciplina."estatistica 1" = 0
disciplina."estatistica 2" = 0
disciplina."estatistica descritiva e probabilidade" = 0
disciplina."estatistica i" = 0
disciplina."estatistica ii" = 0
disciplina."estatistica inferencial" = 0
disciplina."fundamentos de analise" = 1
disciplina."geometria analitica" = 1
disciplina."geometria diferencial" = 1
disciplina."geometria espacial" = -1
disciplina.inferencia = -1
disciplina."introducao a analise no rn" = 1
disciplina."introducao a estatistica" = 1
disciplina."introducao a probabilidade" = 1
disciplina."introducao a teoria qualitativa das edos" = 1
disciplina."matematica discreta" = 0
disciplina."matematica financeira" = 0
disciplina."nocoes de atuaria" = -1
disciplina.probabilidade = 0
disciplina."probabilidade e estatistica" = 0
disciplina."probabilidade e estatistica a" = 0
disciplina."probabilidade e estatistica b" = 0
disciplina."teoria de grupos" = 1
horario.246m12 = 1
horario.246m23 = 1
horario.246m34 = 1
horario.246m45 = 1
horario.246n23 = -1
horario.246n45 = -1
horario.246t12 = -1
horario.246t23 = 0
horario.246t34 = 0
horario.246t45 = 0
horario.246t56 = 0
horario.24m12 = 1
horario.24m23 = 1
horario.24m34 = 1
horario.24m45 = 1
horario.24m56 = 1
horario.24n23 = 0
horario.24n45 = 0
horario.24t12 = -1
horario.24t23 = 0
horario.24t34 = 0
horario.24t45 = 0
horario.24t56 = 0
horario.25t23 = 0
horario.25t45 = 0
horario.35m12 = 1
horario.35m23 = 1
horario.35m34 = 1
horario.35m45 = 1
horario.35m56 = 1
horario.35n23 = 0
horario.35n34 = 0
horario.35n45 = 0
horario.35t12 = -1
horario.35t23 = 0
horario.35t34 = 0
horario.35t45 = 0
horario.35t56 = 0
horario.36t23 = 0
horario.46m12 = 1
horario.46m23 = 1
horario.46m34 = 1
horario.46m45 = 1
horario.46m56 = 1
horario.46n23 = 0
horario.46n45 = 0
horario.46t23 = 0
horario.46t34 = 0
horario.46t45 = 0
horario.46t56 = 0
horario.4t12 = -1
horario.56t23 = 0
horario.5n45 = -1
horario.6m123 = -1
horario.6m23 = -1
horario.6n23 = -1
horario.6t12 = -1
